name: tudat-space
channels:
  - conda-forge
  - tudat-team
dependencies:
  - python=3.11
  - tudatpy
  - matplotlib
  - notebook
  - scipy
  - pandas
  - astropy
  - tqdm      
  - astropy-healpix  
  - spiceypy # for automatic data downloader and kernel converter
  - tabulate
  - colorama
  - numpy<2.0.0
  - pip
  - pip:
    - astroquery>=0.4.8.dev9306

