name: tudat-space
channels:
  - conda-forge
  - tudat-team
dependencies:
  - tudatpy
  - matplotlib
  - notebook
  - scipy
  - pandas
  - astropy
  - numpy<2.0.0
  - pip
  - pip:
    - astroquery>=0.4.8.dev9306

