name: tudat-docs
channels:
  - conda-forge
dependencies:
  - python
  - jinja2
  - sphinx
  - sphinx_rtd_theme
  - sphinx-design
  - sphinx-copybutton
  - sphinx-gallery
  - ipython
  - ipykernel
  - ipympl
  - pandoc
  - pip
  - pip:
    - sphinxcontrib-contentui
    - nbsphinx
