name: tudat-docs
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sphinx=7.4
  - pydata-sphinx-theme
  - sphinx-design=0.6
  - sphinx-copybutton=0.5
  - sphinx-gallery=0.17
  - nbsphinx=0.9
  - ipython
  - ipykernel
  - pandoc
  - sphinx-codeautolink